const SettingsManager = (() => {

    const translations = {
        en: {
            // ── Nav ──
            nav_home: "Home Page", nav_search: "Search Page", nav_analytics: "Analytics Page",
            nav_profile: "Profile Page", nav_settings: "Settings Page", nav_signout: "Sign out",
            // ── Sidebar user ──
            store_owner: "Store Owner", system_admin: "System Admin",
            // ── Page headers ──
            title_home: "Welcome to Owner Portal", title_search: "Search",
            title_analytics: "Analytics", title_profile: "Profile", title_settings: "Settings",
            // ── Settings page ──
            setting_title: "Settings", lang_title: "Language settings",
            lang_desc: "Choose your favourite system language",
            lang_arabic: "Arabic", lang_english: "English",
            appear_title: "Appearance", appear_desc: "Customise the system's appearance to suit your preferences",
            light_mode: "Light Mode", dark_mode: "Dark Mode",
            // ── Home page table ──
            home_loading: "Loading...",
            th_invoice: "# Invoice", th_client: "Client Name", th_amount: "Amount", th_action: "Action",
            // ── Analytics page — card titles ──
            ana_page_title:       "Analysis",
            ana_total_revenue:    "Total Revenue",
            ana_price_dist:       "Total Price Distribution",
            ana_total_invoices:   "Total Invoices",
            ana_avg_order:        "Avg Order Value",
            ana_payment_dist:     "Payment Distribution",
            ana_top_items:        "Top Selling Items",
            ana_monthly_target:   "Monthly Revenue Target",
            ana_sar_target:       "SAR target",
            ana_revenue_trend:    "Revenue Trend",
            ana_demand:           "Product Demand Breakdown",
            ana_recommendations:  "Recommendations",
            currency:             "SAR",
            // ── Analytics page — month picker ──
            ana_select_month: "Month",
            month_jan: "Jan", month_feb: "Feb", month_mar: "Mar", month_apr: "Apr",
            month_may: "May", month_jun: "Jun", month_jul: "Jul", month_aug: "Aug",
            month_sep: "Sep", month_oct: "Oct", month_nov: "Nov", month_dec: "Dec",
            // ── Analytics page — AI / histogram ──
            ana_waiting_model:   "Waiting for model data",
            ana_connect_db:      "Connect your database and AI model to display the predicted revenue based on quantity.",
            ana_histogram_wait:  "The histogram will appear after the model returns real analysis data.",
            ana_ai_tip:          "These smart tips are generated by AI based on your sales, products, and customer activity.",
            // ── Analytics page — dynamic JS strings ──
            ana_no_data:         "No data yet",
            ana_no_month_data:   "No revenue data for this month",
            ana_no_sales:        "No sales data for this month",
            ana_no_invoice:      "No invoice data available for this month",
            ana_no_product:      "No product data for this month",
            ana_no_payment:      "No payment data for this month",
            ana_no_recommend:    "No recommendations available for this month",
            ana_no_trend:        "No trend data available",
            ana_remaining:       "Remaining to target",
            ana_achieved:        "Target achieved",
            ana_sales:           "sales",
            ana_orders:          "orders",
            ana_of_demand:       "of demand",
            // ── Analytics page — legacy keys (kept for compatibility) ──
            ana_day: "Day", ana_week: "Week", ana_month: "Month", ana_year: "Year",
            ana_budget_risk: "Budget Risk - 78%", ana_high_risk: "Status: High Risk",
            ana_view_details: "View Details >", ana_expected: "Expected Spending",
            ana_anomaly: "Anomaly Alerts", ana_anomaly_found: "2 Anomalies Detected",
            ana_invoices: "Invoices", ana_total: "Total",
            ana_payment_methods: "Payment Methods", ana_transactions: "Transactions Overview",
            ana_sys_admin: "System Administrator",
            // ── Profile page ──
            pro_company: "Company Name", pro_facility: "Facility number (CR)",
            pro_auth: "Authorisation information", pro_valid: "valid until 31/12/2026",
            pro_email: "E-mail", pro_change_pass: "Change password", pro_modify: "Edit Profile",
            pro_phone: "Phone Number",
            pro_facility_label: "Facility Name", pro_cr_label: "CR Number",
            pro_phone_label: "Phone Number", pro_email_label: "E-mail",
            pro_save: "Save Changes", pro_cancel: "Cancel",
            pro_cr_badge_label: "CR",
            // ── Avatar picker ──
            avatar_title: "Choose Your Avatar", avatar_sub: "Select an avatar to represent you",
            avatar_male: "Male", avatar_female: "Female",
            // ── Search page ──
            srch_advanced: "Advanced Search", srch_date: "Date",
            srch_all_time: "All Time", srch_this_week: "This Week", srch_this_month: "This Month",
            srch_payment: "Payment Method", srch_all_methods: "All Methods",
            srch_cash: "Cash", srch_mada: "Mada Card", srch_install: "Installments", srch_apple: "Apple Pay",
            srch_amount_range: "Amount Range (SAR)", srch_apply: "Apply Filters",
            srch_min: "Min", srch_max: "Max",
            srch_sys_admin: "System Administrator", srch_admin_portal: "Admin Portal",
            srch_empty_title: "Search for Invoices", srch_empty_sub: "Loading your invoices...",
            srch_placeholder: "Search by name or invoice number...",
            home_search_placeholder: "Search by client name or invoice ID...",
            srch_no_results_title: "No Results Found", srch_no_results_sub: "Try different keywords or adjust the filters.",
            srch_error_loading: "Error loading invoices. Please try again.",
            srch_card_invoice: "# Invoice", srch_card_client: "Client Name",
            srch_card_date: "Date & Time", srch_card_amount: "Amount", srch_card_open: "Open",
            srch_found_one: "invoice found", srch_found_many: "invoices found",
            // ── Invoice modal ──
            modal_loading: "Loading invoice...", modal_error: "Error loading invoice",
            modal_no_items: "No items found",
            modal_tax_invoice: "TAX INVOICE",
            modal_customer: "Customer", modal_payment: "Payment",
            modal_subtotal: "Subtotal", modal_tax: "Tax (15%)", modal_total: "TOTAL",
            modal_qty: "Qty", modal_download: "Download PDF",
        },

        ar: {
            // ── Nav ──
            nav_home: "الرئيسية", nav_search: "البحث", nav_analytics: "التحليلات",
            nav_profile: "الملف الشخصي", nav_settings: "الإعدادات", nav_signout: "تسجيل الخروج",
            // ── Sidebar user ──
            store_owner: "صاحب المتجر", system_admin: "مسؤول النظام",
            // ── Page headers ──
            title_home: "مرحبًا بك في بوابة المالك", title_search: "البحث",
            title_analytics: "التحليلات", title_profile: "الملف الشخصي", title_settings: "الإعدادات",
            // ── Settings page ──
            setting_title: "الإعدادات", lang_title: "إعدادات اللغة",
            lang_desc: "اختر لغة النظام المفضلة لديك",
            lang_arabic: "العربية", lang_english: "الإنجليزية",
            appear_title: "المظهر", appear_desc: "خصّص مظهر النظام وفق تفضيلاتك",
            light_mode: "الوضع الفاتح", dark_mode: "الوضع الداكن",
            // ── Home page table ──
            home_loading: "جارٍ التحميل...",
            th_invoice: "# الفاتورة", th_client: "اسم العميل", th_amount: "المبلغ", th_action: "الإجراء",
            // ── Analytics page — card titles ──
            ana_page_title:       "التحليلات",
            ana_total_revenue:    "إجمالي الإيرادات",
            ana_price_dist:       "توزيع الأسعار الكلي",
            ana_total_invoices:   "إجمالي الفواتير",
            ana_avg_order:        "متوسط قيمة الطلب",
            ana_payment_dist:     "توزيع طرق الدفع",
            ana_top_items:        "الأكثر مبيعاً",
            ana_monthly_target:   "الهدف الشهري للإيرادات",
            ana_sar_target:       "ريال (الهدف)",
            ana_revenue_trend:    "اتجاه الإيرادات",
            ana_demand:           "تفاصيل الطلب على المنتجات",
            ana_recommendations:  "التوصيات",
            currency:             "ريال",
            // ── Analytics page — month picker ──
            ana_select_month: "الشهر",
            month_jan: "يناير",  month_feb: "فبراير", month_mar: "مارس",   month_apr: "أبريل",
            month_may: "مايو",   month_jun: "يونيو",  month_jul: "يوليو",  month_aug: "أغسطس",
            month_sep: "سبتمبر", month_oct: "أكتوبر", month_nov: "نوفمبر", month_dec: "ديسمبر",
            // ── Analytics page — AI / histogram ──
            ana_waiting_model:   "في انتظار بيانات النموذج",
            ana_connect_db:      "قم بتوصيل قاعدة البيانات والنموذج الذكي لعرض توقعات الإيرادات بناءً على الكمية.",
            ana_histogram_wait:  "سيظهر المخطط بعد وصول بيانات التحليل الحقيقية من النموذج.",
            ana_ai_tip:          "هذه النصائح الذكية مُنشأة بواسطة الذكاء الاصطناعي بناءً على مبيعاتك ومنتجاتك ونشاط عملائك.",
            // ── Analytics page — dynamic JS strings ──
            ana_no_data:         "لا توجد بيانات بعد",
            ana_no_month_data:   "لا توجد بيانات إيرادات لهذا الشهر",
            ana_no_sales:        "لا توجد بيانات مبيعات لهذا الشهر",
            ana_no_invoice:      "لا توجد فواتير لهذا الشهر",
            ana_no_product:      "لا توجد بيانات منتجات لهذا الشهر",
            ana_no_payment:      "لا توجد بيانات دفع لهذا الشهر",
            ana_no_recommend:    "لا توجد توصيات لهذا الشهر",
            ana_no_trend:        "لا توجد بيانات اتجاه",
            ana_remaining:       "المتبقي للهدف",
            ana_achieved:        "تم تحقيق الهدف",
            ana_sales:           "مبيعات",
            ana_orders:          "طلبات",
            ana_of_demand:       "من الطلب",
            // ── Analytics page — legacy keys ──
            ana_day: "يوم", ana_week: "أسبوع", ana_month: "شهر", ana_year: "سنة",
            ana_budget_risk: "مخاطر الميزانية - 78%", ana_high_risk: "الحالة: خطر مرتفع",
            ana_view_details: "عرض التفاصيل >", ana_expected: "الإنفاق المتوقع",
            ana_anomaly: "تنبيهات الشذوذ", ana_anomaly_found: "تم اكتشاف شذوذَين",
            ana_invoices: "الفواتير", ana_total: "الإجمالي",
            ana_payment_methods: "طرق الدفع", ana_transactions: "نظرة عامة على المعاملات",
            ana_sys_admin: "مدير النظام",
            // ── Profile page ──
            pro_company: "اسم الشركة", pro_facility: "رقم السجل التجاري (CR)",
            pro_auth: "معلومات الترخيص", pro_valid: "صالح حتى 31/12/2026",
            pro_email: "البريد الإلكتروني", pro_change_pass: "تغيير كلمة المرور", pro_modify: "تعديل الملف الشخصي",
            pro_phone: "رقم الجوال",
            pro_facility_label: "اسم المنشأة", pro_cr_label: "رقم السجل التجاري",
            pro_phone_label: "رقم الجوال", pro_email_label: "البريد الإلكتروني",
            pro_save: "حفظ التعديلات", pro_cancel: "إلغاء",
            pro_cr_badge_label: "س.ت",
            // ── Avatar picker ──
            avatar_title: "اختر صورتك الشخصية", avatar_sub: "اختر الصورة التي تمثلك",
            avatar_male: "ذكر", avatar_female: "أنثى",
            // ── Search page ──
            srch_advanced: "بحث متقدم", srch_date: "التاريخ",
            srch_all_time: "كل الأوقات", srch_this_week: "هذا الأسبوع", srch_this_month: "هذا الشهر",
            srch_payment: "طريقة الدفع", srch_all_methods: "كل الطرق",
            srch_cash: "نقداً", srch_mada: "بطاقة مدى", srch_install: "أقساط", srch_apple: "آبل باي",
            srch_amount_range: "نطاق المبلغ (ريال)", srch_apply: "تطبيق الفلاتر",
            srch_min: "الحد الأدنى", srch_max: "الحد الأقصى",
            srch_sys_admin: "مدير النظام", srch_admin_portal: "بوابة الإدارة",
            srch_empty_title: "ابحث عن الفواتير", srch_empty_sub: "جارٍ تحميل فواتيرك...",
            srch_placeholder: "ابحث باسم العميل أو رقم الفاتورة...",
            home_search_placeholder: "ابحث باسم العميل أو رقم الفاتورة...",
            srch_no_results_title: "لا توجد نتائج", srch_no_results_sub: "جرّب كلمات مختلفة أو عدّل الفلاتر.",
            srch_error_loading: "خطأ في تحميل الفواتير. حاول مرة أخرى.",
            srch_card_invoice: "# الفاتورة", srch_card_client: "اسم العميل",
            srch_card_date: "التاريخ والوقت", srch_card_amount: "المبلغ", srch_card_open: "فتح",
            srch_found_one: "فاتورة واحدة", srch_found_many: "فاتورة موجودة",
            // ── Invoice modal ──
            modal_loading: "جارٍ تحميل الفاتورة...", modal_error: "خطأ في تحميل الفاتورة",
            modal_no_items: "لا توجد عناصر",
            modal_tax_invoice: "فاتورة ضريبية",
            modal_customer: "العميل", modal_payment: "طريقة الدفع",
            modal_subtotal: "المجموع الجزئي", modal_tax: "ضريبة القيمة المضافة (15%)", modal_total: "الإجمالي",
            modal_qty: "الكمية", modal_download: "تنزيل PDF",
        }
    };

    // ════════════════════════════════════════════════
    //  Dark-mode styles  (all pages including analytics)
    // ════════════════════════════════════════════════
    function injectDarkStyles() {
        if (document.getElementById('sm-dark-css')) return;
        const s = document.createElement('style');
        s.id = 'sm-dark-css';
        s.textContent = `
            /* ── General ── */
            body.dark-mode { background-color: #121212 !important; color: #e0e0e0 !important; }
            body.dark-mode .sidebar { background: #1e1e1e !important; border-right-color: #333 !important; }
            body.dark-mode [dir="rtl"] .sidebar { border-left-color: #333 !important; }
            body.dark-mode .nav-item { color: #bbb !important; }
            body.dark-mode .nav-item:hover,
            body.dark-mode .nav-item.active { background-color: #2a2a2a !important; color: #76937C !important; }
            body.dark-mode header { background-color: #1a2a22 !important; }
            body.dark-mode [class*="card"],
            body.dark-mode .settings-card,
            body.dark-mode .modal-box,
            body.dark-mode .table-card,
            body.dark-mode .profile-card,
            body.dark-mode .chart-container {
                background: #1e1e1e !important;
                color: #e0e0e0 !important;
                box-shadow: 0 4px 20px rgba(0,0,0,0.4) !important;
            }
            body.dark-mode .settings-section { background-color: #2a2a2a !important; }
            body.dark-mode .option-btn { background: #333 !important; border-color: #444 !important; color: #ccc !important; }
            body.dark-mode .option-btn.active { border-color: #76937C !important; background: #1e2e23 !important; color: #76937C !important; }
            body.dark-mode input,
            body.dark-mode select,
            body.dark-mode textarea { background: #2a2a2a !important; border-color: #444 !important; color: #e0e0e0 !important; }
            body.dark-mode table { color: #e0e0e0 !important; }
            body.dark-mode th { background: #2a2a2a !important; color: #ddd !important; }
            body.dark-mode td { border-color: #333 !important; }
            body.dark-mode .main-wrapper { background-color: #121212 !important; }
            body.dark-mode .filter-btn { background: #2a2a2a !important; border-color: #444 !important; color: #ccc !important; }
            body.dark-mode .filter-btn.active { background: #1a2a22 !important; color: #76937C !important; }

            /* ── Analytics page specific ── */
            body.dark-mode .dashboard {
                background: linear-gradient(180deg, #1a1a1a 0%, #121212 100%) !important;
            }
            body.dark-mode .page-title { color: #8fb896 !important; }
            body.dark-mode .card {
                background: rgba(30,30,30,0.98) !important;
                border-color: rgba(118,147,124,0.2) !important;
                box-shadow: 0 10px 28px rgba(0,0,0,0.4) !important;
            }
            body.dark-mode .card-title { color: #8fb896 !important; }
            body.dark-mode .big-number { color: #e0e0e0 !important; }
            body.dark-mode .currency-label { color: #8fb896 !important; }
            body.dark-mode .ai-subtext { color: #777 !important; }
            body.dark-mode .empty-note { color: #555 !important; }

            /* Month picker */
            body.dark-mode .month-list {
                background: rgba(30,30,30,0.98) !important;
                border-color: rgba(118,147,124,0.2) !important;
                box-shadow: 0 18px 42px rgba(0,0,0,0.5) !important;
            }
            body.dark-mode .month-list div { color: #8fb896 !important; }
            body.dark-mode .month-list div:hover,
            body.dark-mode .month-list div.active-month {
                background: #2a2a2a !important;
                color: #c5dfc8 !important;
            }

            /* Target card */
            body.dark-mode .target-input {
                background: #2a2a2a !important;
                border-color: #444 !important;
                color: #e0e0e0 !important;
            }
            body.dark-mode .target-currency { color: #8fb896 !important; }
            body.dark-mode .target-text { color: #aaa !important; }

            /* Revenue trend */
            body.dark-mode .trend-box {
                background: linear-gradient(180deg, rgba(30,46,34,0.6), rgba(18,18,18,0.9)) !important;
                border-color: rgba(118,147,124,0.2) !important;
            }
            body.dark-mode .trend-month-labels {
                background: rgba(18,18,18,0.9) !important;
                border-color: rgba(118,147,124,0.2) !important;
            }
            body.dark-mode .trend-month-labels span { color: #666 !important; }

            /* Breakdown / categories */
            body.dark-mode .category-item {
                background: rgba(40,40,40,0.8) !important;
            }
            body.dark-mode .cat-name { color: #e0e0e0 !important; }
            body.dark-mode .cat-sub  { color: #777 !important; }
            body.dark-mode .cat-amount { color: #8fb896 !important; }

            /* Payment legend */
            body.dark-mode .pay-legend-item { color: #ccc !important; }

            /* Top items */
            body.dark-mode .item-row {
                color: #ccc !important;
                border-bottom-color: #333 !important;
            }

            /* Recommendations */
            body.dark-mode .recommendation-item { color: #ccc !important; }
            body.dark-mode .recommendation-text { color: #ccc !important; }

            /* AI histogram */
            body.dark-mode .revenue-ai-chart-wrap {
                background: rgba(30,30,30,0.72) !important;
                border-color: rgba(118,147,124,0.2) !important;
            }
            body.dark-mode .histogram-empty-state { color: #8fb896 !important; }
            body.dark-mode .histogram-empty-state p { color: #666 !important; }
            body.dark-mode .histogram-empty-state .empty-state-icon {
                background: rgba(118,147,124,0.15) !important;
            }

            /* Tooltip */
            body.dark-mode .tooltip {
                background: #2a2a2a !important;
                color: #e0e0e0 !important;
                border: 1px solid rgba(118,147,124,0.3) !important;
                box-shadow: 0 18px 42px rgba(0,0,0,0.5) !important;
            }
            body.dark-mode .tooltip:before {
                background: rgba(118,147,124,0.15) !important;
                color: #8fb896 !important;
            }
            body.dark-mode .tooltip:after {
                background: #2a2a2a !important;
                border-color: rgba(118,147,124,0.3) !important;
            }

            /* Menu icon */
            body.dark-mode .menu-icon {
                background: rgba(30,30,30,0.95) !important;
                border-color: rgba(118,147,124,0.3) !important;
            }
            body.dark-mode .menu-icon span { background: #8fb896 !important; }

            /* Info buttons */
            body.dark-mode .info-icon,
            body.dark-mode .clean-info-button,
            body.dark-mode .revenue-info-button {
                background: #2a2a2a !important;
                color: #8fb896 !important;
                border-color: rgba(118,147,124,0.4) !important;
            }
        `;
        (document.head || document.getElementsByTagName('head')[0]).appendChild(s);
    }

    // ════════════════════════════════════════════════
    //  Core functions
    // ════════════════════════════════════════════════
    function applyDarkMode(isDark) {
        injectDarkStyles();
        const apply = () => document.body && document.body.classList.toggle('dark-mode', isDark);
        if (document.body) apply();
        else document.addEventListener('DOMContentLoaded', apply);
    }

    function applyLanguage(lang) {
        const t = translations[lang] || translations.en;
        const isAr = lang === 'ar';

        document.documentElement.lang = lang;
        document.documentElement.dir = isAr ? 'rtl' : 'ltr';

        // data-i18n  →  textContent
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (t[key] !== undefined) el.textContent = t[key];
        });

        // data-i18n-val  →  textContent
        document.querySelectorAll('[data-i18n-val]').forEach(el => {
            const key = el.getAttribute('data-i18n-val');
            if (t[key] !== undefined) el.textContent = t[key];
        });

        // data-i18n-placeholder  →  placeholder attribute
        document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (t[key] !== undefined) el.placeholder = t[key];
        });

        if (document.body)
            document.body.style.fontFamily = isAr
                ? "'Tahoma','Arial',sans-serif"
                : "'Segoe UI',sans-serif";
    }

    function init() {
        const lang = localStorage.getItem('sj_language') || 'en';
        const dark = localStorage.getItem('sj_dark_mode') === 'true';
        applyDarkMode(dark);
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => applyLanguage(lang));
        } else {
            applyLanguage(lang);
        }
        window.addEventListener('load', () => applyLanguage(lang));
    }

    function setLanguage(lang) { localStorage.setItem('sj_language', lang); applyLanguage(lang); }
    function setDarkMode(isDark) { localStorage.setItem('sj_dark_mode', isDark ? 'true' : 'false'); applyDarkMode(isDark); }
    function getLanguage() { return localStorage.getItem('sj_language') || 'en'; }
    function isDarkMode()  { return localStorage.getItem('sj_dark_mode') === 'true'; }
    function getT(key) {
        const lang = getLanguage();
        const t = translations[lang] || translations.en;
        return t[key] !== undefined ? t[key] : (translations.en[key] || key);
    }

    return { init, setLanguage, setDarkMode, getLanguage, isDarkMode, applyLanguage, getT };
})();

SettingsManager.init();